Added _Partial, _Fields, and _Patch structs for all records
PapaCharlie/go-restli pull request #7
Opened 2020-04-20 01:56 UTC by bored-engineer

Adds `_Partial`, `_Fields` and `_Patch` structs for each record type, ex:
```
type Address struct {
	Street string `json:"street"`
}

type Address_Partial struct {
	Street *string `json:"street,omitempty"`
}

type Address_Fields struct {
	Street bool
}

type Address_Patch struct {
	Set    *Address_Partial
	Delete Address_Fields
}
```
The `_Fields` struct implement a custom `Stringer` and `json.Marshaller` interface which converts the `true` fields into a `[]string`. 

To accomplish this with minimal allocations, a new exported method `GatherFields(prefix string, fields *[]string)` is added to all `_Fields` structs which adds each set field to `fields` with `prefix`. Internally if a `_Fields` struct contains another `_Fields` struct the `GatherFields` method is used. The method must be exported to support conflict resolution/cross package nested Fields.

There are no tests added in this PR as this is just field/struct generation, usage of the structs will require tests.

2020-04-22 02:27 UTC, PapaCharlie requested changes
Plus what we're chatting about on Slack

2020-04-22 02:27 UTC, PapaCharlie commented on internal/codegen/record.go
> +		fmt.Sprintf("%s is %s but with optional values", r.PartialName(), r.Name),
`"%s is %s where all fields can be optionally set. Intended for use with patch requests and projections"`

2020-04-22 02:27 UTC, PapaCharlie commented on internal/codegen/record.go
> +			fields.Tag(JsonFieldTag("$delete", true))
```go
def.Id("Update")
    .Qual(r.PackagePath(), r.PartialName())
    .Tag(JsonFieldTag("$set", true))
def.Id("Delete")
    .Qual(r.PackagePath(), r.FieldsName())
    .Tag(JsonFieldTag("$delete", true))
```

2020-04-22 02:27 UTC, PapaCharlie commented on internal/codegen/codefile.go
> +	GatherFields = "GatherFields"
Given that the type will be `_Fields`, just calling it `Gather` should be fine, otherwise it feels redundant

2020-04-22 02:27 UTC, PapaCharlie commented on internal/codegen/record.go
> +		fmt.Sprintf("%s is a list of fields in *%s and *%s", r.FieldsName(), r.Name, r.PartialName()),
I think it'd be best to show intent here:
> {r.FieldsName} is used to represent a selection of the fields from {r.Name}. Toggling the value of a field represents selecting it for a projection

2020-04-22 02:27 UTC, PapaCharlie commented on internal/codegen/record.go
> +				AddWordWrappedComment(field, f.Doc).Line()
Conversely, given that the type of these fields isn't going to be the same as the corresponding types in the record, is adding the documentation here correct?

2020-04-22 02:29 UTC, PapaCharlie requested changes

2020-04-22 02:29 UTC, PapaCharlie commented on internal/codegen/type.go
> +func (t *RestliType) IsFieldRecord() bool {
I think this can just be `IsRecord` right?

2020-04-22 02:29 UTC, bored-engineer commented on internal/codegen/record.go
> +				AddWordWrappedComment(field, f.Doc).Line()
The reason I left it in is so someone using a tooltip/godoc can understand what field they are fetching based on the doc. Ex: making a request for a obj and trying to decide what projections to use

2020-04-22 21:09 UTC, PapaCharlie commented on internal/codegen/record.go
> +				AddWordWrappedComment(field, f.Doc).Line()
Makes sense

2020-04-24 04:25 UTC, bored-engineer commented
Looks like this has a bug with generating nested `_Partial` structs I have to track down, please don't merge this yet

2020-07-24 19:09 UTC, PapaCharlie commented
Changes partially checked in with support for partial_update

2020-07-24 19:09 UTC, closed without merging